version: "3.7"
services:
  service_a:
    build:
      context: .
      dockerfile: Dockerfile.server
    networks:
      - envoymesh
    expose:
      - "3001"
    ports:
      - "3001:3001"
      
  envoy:
    build:
      context: .
      dockerfile: Dockerfile.envoy
    volumes:
      - ./envoy.yaml:/tmp/envoy/envoy.yaml
    networks:
      - envoymesh
    expose:
      - "9901"
      - "8090"
    ports:
      - "9901:9901"
      - "8090:8090"

networks:
  envoymesh: {}
